### ISSUE TITLE
The extension is not working on Nov 2017 desktop version

### ISSUE THREAD

**Issue by kavitav25** [q2g/q2g-ext-listbox#16]
Hello,

Can u please help me with the issue?

**Comment by konne** [comment]
please can you write more details

**Comment by kavitav25** [comment]
![image](https://user-images.githubusercontent.com/31730121/38600212-006fc856-3d81-11e8-8e4f-d8b67dafb0bc.png)

Please look into the screenshot.

**Comment by konne** [comment]
Do you used the binary download package? https://m.sense2go.net/extension-package
Or do you just cloned the github Repo -> you have to compile the repo, to get it working

**Comment by kavitav25** [comment]
I have downloaded from GitHub...

**Comment by konne** [comment]
when you have to compile it like it is described in the main Readme

**Comment by kavitav25** [comment]
Please help me to understand more in detail...
I have tried opening Readme File but I am unable to open it.

Please look into the below screenshot:

![image](https://user-images.githubusercontent.com/31730121/38718930-1912d276-3f0d-11e8-8696-3a556011ddbe.png)

![image](https://user-images.githubusercontent.com/31730121/38718912-075d0ea2-3f0d-11e8-8343-8a75582f7fd0.png)

Regards,
Kavita

**Comment by konne** [comment]
here the content:

COMPILE from Source

    Clone the Github Repo into extension directory
    Install nodejs
    Open Node.js command prompt
    npm install
    npm run build
